### ISSUE TITLE
Does the isotope-packery integration support drag drop?

### ISSUE THREAD

**Issue by dcworldwide** [metafizzy/isotope-packery#13]
Firstly, great project! Thankyou.

I need to use isotope's sorting/filters + packery's drag drop features. Does this project support these features? I'd really like to know more about this project. I.e. is this a complete implementation of the isotope and packery projects respectively, or is this a subset of those projects?

**Comment by desandro** [comment]
Hello! Dragging is not supported with Packery layout mode for Isotope. See https://github.com/metafizzy/packery/issues/46#issuecomment-18617291 for why I do not wish to mix filtering with draggability.
