### ISSUE TITLE
"isotope": "^3.0.0" not available?

### ISSUE THREAD

**Issue by affectsoftware** [metafizzy/isotope-packery#14]
isotope 3.0.0? not resolvable via bower? (but it's mentioned in your new bower.json)

bower update is broken

```bower isotope#^3.0.0                                   ENORESTARGET No tag found that was able to satisfy ^3.0.0```

**Comment by mattgrannary** [comment]
Same thing with npm

**Comment by desandro** [comment]
I just released Isotope v3 today. This should now be resolved. Thanks for the heads up!
