### ISSUE TITLE
Is there a way to improve packing?

### ISSUE THREAD

**Issue by clarknelson** [metafizzy/isotope-packery#18]
![screen shot 2018-12-20 at 12 49 57 pm](https://user-images.githubusercontent.com/4106671/50304637-18209d80-0456-11e9-9774-66aa14ae4024.png)

Here you can see that two items which could fit side by side are stacked. Idk why this would be happening :( The example above is not too bad, but check out this layout.

![screen shot 2018-12-20 at 12 53 11 pm](https://user-images.githubusercontent.com/4106671/50304697-47cfa580-0456-11e9-8cfd-71a168523bdf.png)

Only two of the four available columns are being filled 😫

Any thoughts on how to improve this?

**Comment by desandro** [comment]
1. Double check that `layoutMode: 'packery'` is set
2. Double check if you're using `{ packery: { columnWidth }}` and, if so, how the item sizes fit within that.

**Comment by clarknelson** [comment]
this.iso = new Isotope('.project-grid', {
      itemSelector: '.project-preview-item',
      layoutMode: 'packery',
      packery: {
        gutter: '.project-preview-gutter',
        columnWidth: '.project-preview-item'
      }
      // layoutMode: 'masonry',
      // masonry: {
      //   gutter: '.project-preview-gutter',
      //   columnWidth: '.project-preview-item',
      //   horizontalOrder: true
      // }
    });

**Comment by clarknelson** [comment]
actually _removing_ `columnWidth` fixes the layout. Maybe you do not need to specify this AND `itemSelector`.

**Comment by clarknelson** [comment]
using `columnWidth: Math.floor($('.project-preview-item').innerWidth())` doesn't fix it, even though I was 99% sure that was the issue

**Comment by desandro** [comment]
Do you have a live URL I could take a look at?   Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by clarknelson** [comment]
We went live, the issue was fixed :) https://workwithfocus.com/portfolio

When I removed `packery: { columnWidth: '.project-preview-item' }` the items filled in correctly
