### ISSUE TITLE
Javascript error, dragging in IE8

### ISSUE THREAD

**Issue by akostajti** [metafizzy/isotope-packery#3]
After dragging a few elements sometimes (I can't tell when, it seems to come randomly) I get this js error:

`'position' is null or not an object`

![js error](https://cloud.githubusercontent.com/assets/508263/4230325/4e4adc8e-3982-11e4-911d-4a4167319bd4.png)

Line 631 contains this code:

`_this.itemDragMove( event.currentTarget, ui.position.left, ui.position.top );`

**Comment by desandro** [comment]
The packery layout mode for Isotope does not support dragging. I recommend you use the separate [Packery library](http://packery.metafizzy.co/) for dragging.
